<!DOCTYPE firma
[
<!ELEMENT firma (comenzi)>
<!ELEMENT comenzi (comanda+)>
<!ELEMENT comanda (IDcomanda, tipComanda, tipColet, colet, curier, data)>
<!ELEMENT IDcomanda (#PCDATA)>
<!ELEMENT tipComanda (#PCDATA)>
<!ELEMENT tipColet (#PCDATA)>
<!ELEMENT colet (IDcolet, greutate, dimensiuni, expeditor, destinatar)>
<!ELEMENT IDcolet (#PCDATA)>
<!ELEMENT greutate (#PCDATA)>
<!ELEMENT dimensiuni (inaltime, latime, lungime)>
<!ELEMENT inaltime (#PCDATA)>
<!ELEMENT latime (#PCDATA)>
<!ELEMENT lungime (#PCDATA)>
<!ELEMENT expeditor (nume, prenume, telefon, adresa)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT adresa (judet, oras, strada, numar, bloc, apartament)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT oras (#PCDATA)>
<!ELEMENT strada (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT bloc (#PCDATA)>
<!ELEMENT apartament (#PCDATA)>
<!ELEMENT destinatar (nume, prenume, telefon, adresa)>
<!ELEMENT curier (IDcurier, nume, prenume, telefon, masina)>
<!ELEMENT IDcurier (#PCDATA)>
<!ELEMENT masina (marca, model, numarInmatriculare, tipMasina, anFabricatie, culoare)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT numarInmatriculare (#PCDATA)>
<!ELEMENT tipMasina (#PCDATA)>
<!ELEMENT anFabricatie (#PCDATA)>
<!ELEMENT culoare (#PCDATA)>
<!ELEMENT data (an, luna, zi, ora)>
<!ELEMENT an (#PCDATA)>
<!ELEMENT luna (#PCDATA)>
<!ELEMENT zi (#PCDATA)>
<!ELEMENT ora (#PCDATA)>
]>

<firma>
    <comenzi>
        <comanda>
            <IDcomanda>11</IDcomanda>
            <tipComanda>livrare</tipComanda>
            <tipColet>plic</tipColet>
            <colet>
                <IDcolet>103</IDcolet>
                <greutate>1</greutate>
                <dimensiuni>
                    <inaltime>15</inaltime>
                    <latime>15</latime>
                    <lungime>20</lungime>
                </dimensiuni>
                <expeditor>
                    <nume>BearingPoint SRL</nume>
                    <prenume>-</prenume>
                    <telefon>0700000000</telefon>
                    <adresa>
                        <judet>Bucuresti</judet>
                        <oras>Bucuresti</oras>
                        <strada>Strada Izvor</strada>
                        <numar>80</numar>
                        <bloc>-</bloc>
                        <apartament>-</apartament>
                    </adresa>        
                </expeditor>
                <destinatar>
                    <nume>Eduard</nume>
                    <prenume>Lache</prenume>
                    <telefon>0798765432</telefon>
                    <adresa>
                        <judet>Bucuresti</judet>
                        <oras>Bucuresti</oras>
                        <strada>Splaiul Independentei</strada>
                        <numar>290</numar>
                        <bloc>P16</bloc>
                        <apartament>433</apartament>
                    </adresa>
                </destinatar>
            </colet>
            <curier>
                <IDcurier>122</IDcurier>
                <nume>Vasiliu</nume>
                <prenume>Ion</prenume>
                <telefon>0789876543</telefon>
                <masina>
                    <marca>BMW</marca>
                    <model>M4</model>
                    <numarInmatriculare>B123ASD</numarInmatriculare>
                    <tipMasina>Sedan</tipMasina>
                    <anFabricatie>2010</anFabricatie>
                    <culoare>negru</culoare>
                </masina>
            </curier>
            <data>
                <an>2017</an>
                <luna>04</luna>
                <zi>25</zi>
                <ora>16:00</ora>
            </data>
        </comanda>
        
        <comanda>
            <IDcomanda>12</IDcomanda>
            <tipComanda>ridicare</tipComanda>
            <tipColet>pachet</tipColet>
            <colet>
                <IDcolet>108</IDcolet>
                <greutate>16</greutate>
                <dimensiuni>
                    <inaltime>25</inaltime>
                    <latime>35</latime>
                    <lungime>80</lungime>
                </dimensiuni>
                <expeditor>
                    <nume>eMag SRL</nume>
                    <prenume>-</prenume>
                    <telefon>0701230000</telefon>
                    <adresa>
                        <judet>Bucuresti</judet>
                        <oras>Bucuresti</oras>
                        <strada>Strada Crangasi</strada>
                        <numar>32</numar>
                        <bloc>-</bloc>
                        <apartament>-</apartament>
                    </adresa>        
                </expeditor>
                <destinatar>
                    <nume>Eduard</nume>
                    <prenume>Lache</prenume>
                    <telefon>0798765432</telefon>
                    <adresa>
                        <judet>Bucuresti</judet>
                        <oras>Bucuresti</oras>
                        <strada>Splaiul Independentei</strada>
                        <numar>290</numar>
                        <bloc>P16</bloc>
                        <apartament>433</apartament>
                    </adresa>
                </destinatar>
            </colet>
            <curier>
                <IDcurier>122</IDcurier>
                <nume>Alexandrescu</nume>
                <prenume>Daniel</prenume>
                <telefon>0789873343</telefon>
                <masina>
                    <marca>Audi</marca>
                    <model>RS8</model>
                    <numarInmatriculare>B222ZZZ</numarInmatriculare>
                    <tipMasina>Limuzina</tipMasina>
                    <anFabricatie>2014</anFabricatie>
                    <culoare>rosu</culoare>
                </masina>
            </curier>
            <data>
                <an>2017</an>
                <luna>04</luna>
                <zi>29</zi>
                <ora>20:00</ora>
            </data>
        </comanda>

        <comanda>
            <IDcomanda>14</IDcomanda>
            <tipComanda>ridicare</tipComanda>
            <tipColet>pachet</tipColet>
            <colet>
                <IDcolet>111</IDcolet>
                <greutate>50</greutate>
                <dimensiuni>
                    <inaltime>100</inaltime>
                    <latime>100</latime>
                    <lungime>100</lungime>
                </dimensiuni>
                <expeditor>
                    <nume>Universitatea POLITEHNICA</nume>
                    <prenume>-</prenume>
                    <telefon>0219800000</telefon>
                    <adresa>
                        <judet>Bucuresti</judet>
                        <oras>Bucuresti</oras>
                        <strada>Bulevardul Iuliu Maniu</strada>
                        <numar>290</numar>
                        <bloc>-</bloc>
                        <apartament>-</apartament>
                    </adresa>        
                </expeditor>
                <destinatar>
                    <nume>Eduard</nume>
                    <prenume>Lache</prenume>
                    <telefon>0798765432</telefon>
                    <adresa>
                        <judet>Bucuresti</judet>
                        <oras>Bucuresti</oras>
                        <strada>Splaiul Independentei</strada>
                        <numar>290</numar>
                        <bloc>P16</bloc>
                        <apartament>433</apartament>
                    </adresa>
                </destinatar>
            </colet>
            <curier>
                <IDcurier>122</IDcurier>
                <nume>Antonescu</nume>
                <prenume>Andrei</prenume>
                <telefon>0789876543</telefon>
                <masina>
                    <marca>Mercedes</marca>
                    <model>Sprinter</model>
                    <numarInmatriculare>B333BBB</numarInmatriculare>
                    <tipMasina>Duba</tipMasina>
                    <anFabricatie>2016</anFabricatie>
                    <culoare>alb</culoare>
                </masina>
            </curier>
            <data>
                <an>2017</an>
                <luna>05</luna>
                <zi>11</zi>
                <ora>12:30</ora>
            </data>
        </comanda>

        <comanda>
            <IDcomanda>14</IDcomanda>
            <tipComanda>livrare</tipComanda>
            <tipColet>pachet</tipColet>
            <colet>
                <IDcolet>111</IDcolet>
                <greutate>50</greutate>
                <dimensiuni>
                    <inaltime>100</inaltime>
                    <latime>100</latime>
                    <lungime>100</lungime>
                </dimensiuni>
                <expeditor>
                    <nume>Universitatea POLITEHNICA Bucuresti SRL</nume>
                    <prenume>-</prenume>
                    <telefon>0219800000</telefon>
                    <adresa>
                        <judet>Bucuresti</judet>
                        <oras>Bucuresti</oras>
                        <strada>Bulevardul Iuliu Maniu</strada>
                        <numar>290</numar>
                        <bloc>-</bloc>
                        <apartament>-</apartament>
                    </adresa>        
                </expeditor>
                <destinatar>
                    <nume>Eduard</nume>
                    <prenume>Lache</prenume>
                    <telefon>0798765432</telefon>
                    <adresa>
                        <judet>Bucuresti</judet>
                        <oras>Bucuresti</oras>
                        <strada>Splaiul Independentei</strada>
                        <numar>290</numar>
                        <bloc>P16</bloc>
                        <apartament>433</apartament>
                    </adresa>
                </destinatar>
            </colet>
            <curier>
                <IDcurier>122</IDcurier>
                <nume>Antonescu</nume>
                <prenume>Andrei</prenume>
                <telefon>0789876543</telefon>
                <masina>
                    <marca>Mercedes</marca>
                    <model>Sprinter</model>
                    <numarInmatriculare>B333BBB</numarInmatriculare>
                    <tipMasina>Duba</tipMasina>
                    <anFabricatie>2000</anFabricatiean>
                    <culoare>negru</culoare>
                </masina>
            </curier>
            <data>
                <an>2017</an>
                <luna>05</luna>
                <zi>11</zi>
                <ora>12:30</ora>
            </data>
        </comanda>
    </comenzi>
</firma>